<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>KasirPro.Keygen</RootNamespace>
    <AssemblyName>KasirPro.Keygen</AssemblyName>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Version>1.1.0</Version>
    <Product>KasirPro License Manager</Product>
    <Company>KasirPro</Company>
    <AssemblyTitle>KasirPro Master Keygen</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.28" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="6.0.36" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\KasirPro.Licensing\KasirPro.Licensing.csproj" />
  </ItemGroup>

</Project>

