<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>KasirPro.Licensing</RootNamespace>
    <AssemblyName>KasirPro.Licensing</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="6.0.2" />
  </ItemGroup>

</Project>
