using System.Security.Cryptography;
using System.Text.Json;

namespace KasirPro.Licensing;

/// <summary>Result of checking the stored license at app startup.</summary>
public class LicenseCheckResult
{
    public bool Activated { get; set; }
    public string Message { get; set; } = "";
    public LicensePayload? Payload { get; set; }
}

/// <summary>
/// Holds the embedded PUBLIC key only. The private master key never ships with the POS app.
/// Replace this value after running the Keygen's "Export Public Key" once, before building a release.
/// </summary>
public static class EmbeddedPublicKey
{
    /// <summary>ECDSA P-256 public key (PEM, SPKI) generated by KasirPro.Keygen.</summary>
    public const string Xml =
@"-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE6K/d1jp5oLELfvD06dg0+Iiswq25
y6jboVmRMWLK95PAEBWdgOtJ8Du7k5Yb1gMk8O/wvQYPJeoLF432DG5P8Q==
-----END PUBLIC KEY-----";

    public static bool IsConfigured =>
        !string.IsNullOrWhiteSpace(Xml) && Xml != "REPLACE_WITH_PUBLIC_KEY_PEM";

    /// <summary>Short fingerprint of the embedded public key (compare with Keygen's).</summary>
    public static string Fingerprint()
    {
        using var key = Create();
        return FingerprintOf(key);
    }

    public static string FingerprintOf(ECDsa key)
    {
        using var sha = System.Security.Cryptography.SHA256.Create();
        var hash = sha.ComputeHash(key.ExportSubjectPublicKeyInfo());
        return Convert.ToHexString(hash)[..16];
    }

    public static ECDsa Create()
    {
        if (!IsConfigured)
            throw new InvalidOperationException(
                "Public key belum dikonfigurasi. Jalankan KasirPro.Keygen -> Export Public Key, lalu timpa konstanta EmbeddedPublicKey.Xml.");
        var ecdsa = ECDsa.Create();
        ecdsa.ImportFromPem(Xml);
        return ecdsa;
    }
}

/// <summary>
/// Activation state manager for the POS app. license.dat is stored next to the executable (portable),
/// and is ALWAYS verified cryptographically at every startup - never trusted as a plain flag.
/// </summary>
public class LicenseActivation
{
    private readonly string _licenseFilePath;
    private readonly string _publicKeyXml;

    public LicenseActivation(string? licenseFilePath = null, string? publicKeyXml = null)
    {
        _licenseFilePath = licenseFilePath ?? Path.Combine(AppContext.BaseDirectory, "license.dat");
        _publicKeyXml = publicKeyXml ?? EmbeddedPublicKey.Xml;
    }

    public string LicenseFilePath => _licenseFilePath;

    public MachineInfo GetMachineInfo() => new()
    {
        DisplayId = MachineId.Get(),
        FullHash = MachineId.FullHash()
    };

    /// <summary>Validate a pasted license token against this machine and persist license.dat on success.</summary>
    public LicenseVerifyResult Activate(string token)
    {
        var result = VerifyToken(token);
        if (result.Status != LicenseVerifyStatus.Valid)
            return result;

        var envelope = new LicenseEnvelope
        {
            Format = "KASIRPRO-LICENSE-V1",
            Token = token.Trim()
        };
        File.WriteAllText(_licenseFilePath, JsonSerializer.Serialize(envelope, new JsonSerializerOptions { WriteIndented = true }));
        return result;
    }

    /// <summary>Startup check: read license.dat and verify signature + machine + expiry.</summary>
    public LicenseCheckResult CheckStoredLicense()
    {
        try
        {
            if (!File.Exists(_licenseFilePath))
                return new LicenseCheckResult { Activated = false, Message = "License not found" };

            LicenseEnvelope? envelope;
            try
            {
                envelope = JsonSerializer.Deserialize<LicenseEnvelope>(File.ReadAllText(_licenseFilePath));
            }
            catch (JsonException)
            {
                return new LicenseCheckResult { Activated = false, Message = "Corrupted License" };
            }

            if (envelope == null || string.IsNullOrWhiteSpace(envelope.Token))
                return new LicenseCheckResult { Activated = false, Message = "Corrupted License" };

            var result = VerifyToken(envelope.Token);
            return new LicenseCheckResult
            {
                Activated = result.Status == LicenseVerifyStatus.Valid,
                Message = result.Message,
                Payload = result.Payload
            };
        }
        catch (IOException)
        {
            return new LicenseCheckResult { Activated = false, Message = "Corrupted License" };
        }
        catch (UnauthorizedAccessException)
        {
            return new LicenseCheckResult { Activated = false, Message = "Cannot read license.dat (access denied)" };
        }
    }

    private LicenseVerifyResult VerifyToken(string token)
    {
        try
        {
            using var key = ECDsa.Create();
            key.ImportFromPem(_publicKeyXml);
            return LicenseToken.Verify(token, key);
        }
        catch (FormatException)
        {
            return LicenseVerifyResult.Fail(LicenseVerifyStatus.Corrupted);
        }
        catch (CryptographicException)
        {
            return LicenseVerifyResult.Fail(LicenseVerifyStatus.InvalidSignature);
        }
    }
}

public class MachineInfo
{
    public string DisplayId { get; set; } = "";
    public string FullHash { get; set; } = "";
}

public class LicenseEnvelope
{
    [System.Text.Json.Serialization.JsonPropertyOrder(-1)]
    [System.Text.Json.Serialization.JsonPropertyName("format")]
    public string Format { get; set; } = "KASIRPRO-LICENSE-V1";

    [System.Text.Json.Serialization.JsonPropertyName("token")]
    public string Token { get; set; } = "";
}
